language: php

php:
  - 7.3
  - 7.4

sudo: false

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
- bash <(curl -s https://codecov.io/bash)
